sudo: required
dist: xenial

addons:
  snaps:
    - name: dotnet-sdk
      confinement: classic
      channel: lts/stable

language: csharp
mono: none
solution: Comp 1.sln

before_script:
  sudo snap alias dotnet-sdk.dotnet dotnet

script:
  - dotnet restore
  - dotnet build
  - dotnet test MSUnitTestProject
  - dotnet test MSUnitTestProject1
  - dotnet test XUnitTestProject
